"""The template's CHANGELOG.md entries an update carries in its commit body."""

from __future__ import annotations

import pytest

from pyfr_cli import changelog
from pyfr_cli.versions import Version

TEXT = """\
# Changelog

Generated by Commitizen. Never edited by hand.

## v0.12.0 (2026-09-20)

### Feat

- let a generated project update itself from the template (#60)

## v0.11.0 (2026-09-18)

### Feat

- add pyfr-cli with pyfr update and update-check (#55)

### Fix

- render both bounds in generated config docs

## v0.10.0 (2026-09-14)

### Feat

- prove a generated project passes its own gates and close m7 (#50)
"""
TEMPLATE = "https://github.com/EmadMokhtar/pyfr"


def test_sections_are_parsed_in_file_order_with_their_bodies() -> None:
    parsed = changelog.sections(TEXT)
    assert [version for version, _, _ in parsed] == [
        Version(0, 12, 0),
        Version(0, 11, 0),
        Version(0, 10, 0),
    ]
    _version, rest, body = parsed[1]
    assert rest == " (2026-09-18)"
    assert body.startswith("### Feat")
    assert "render both bounds" in body
    assert "close m7" not in body


def test_entries_take_the_half_open_range_newest_first_with_links() -> None:
    body = changelog.entries(TEXT, Version(0, 10, 0), Version(0, 12, 0), TEMPLATE)
    assert body.index("v0.12.0") < body.index("v0.11.0")
    assert "v0.10.0" not in body
    assert (
        "## [v0.12.0](https://github.com/EmadMokhtar/pyfr/releases/tag/v0.12.0)"
        " (2026-09-20)"
    ) in body
    assert "- add pyfr-cli with pyfr update and update-check (#55)" in body
    assert body.endswith("\n")


def test_entries_is_empty_when_nothing_is_in_range() -> None:
    assert changelog.entries(TEXT, Version(0, 12, 0), Version(0, 12, 0), TEMPLATE) == ""
    assert changelog.entries("", Version(0, 1, 0), Version(9, 0, 0), TEMPLATE) == ""


@pytest.mark.parametrize(
    "url",
    [
        TEMPLATE,
        TEMPLATE + "/",
        TEMPLATE + ".git",
        "git@github.com:EmadMokhtar/pyfr.git",
        "git@github.com:EmadMokhtar/pyfr",
        "ssh://git@github.com/EmadMokhtar/pyfr.git",
        "ssh://git@github.com/EmadMokhtar/pyfr/",
    ],
)
def test_release_url_normalises_the_template_url(url: str) -> None:
    assert (
        changelog.release_url(url, Version(0, 12, 0))
        == "https://github.com/EmadMokhtar/pyfr/releases/tag/v0.12.0"
    )
